# Generated by Django 4.0.6 on 2022-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year_in_school',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2),
        ),
    ]
