# Generated by Django 4.0.6 on 2022-11-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='year_in_school',
            new_name='language',
        ),
    ]
